# Alternate analysis (following suggestions in review from Hunt)
## stash old data
```{r}
save(TSresults10,TSresults10.pca,TSresults5,TSresults5.pca,file = "combined_TS_results.RData")
rm(TSresults10,TSresults10.pca,TSresults5,TSresults5.pca)
```

## define new functions
```{r}
source("functions.R")
```

```{r}
dimnamelist <- dimnamelist.pca <- vector(mode = "list",length = length(meas))
names(dimnamelist) <- names(dimnamelist.pca) <- names(meas)
for (m in 1:length(dimnamelist)) {
  dimnamelist[[m]] <- dimnamelist.pca[[m]] <- vector(mode = "list", length = length(meas[[m]]))
  names(dimnamelist[[m]]) <- names(dimnamelist.pca[[m]]) <- names(meas[[m]])
  for (n in 1:length(dimnamelist[[m]])) {
    dimnamelist[[m]][[n]] <- colnames(meas[[m]][[n]])[which(!colnames(meas[[m]][[n]]) %in% c("CatNo", "Side", "Sex", "Collection", "Pit", "AssignedAge", "Bin", "repno"))]
    dimnamelist.pca[[m]][[n]] <- colnames(measpc[[m]][[n]])[which(grepl("PC", 
                                                      colnames(measpc[[m]][[n]])))]
  }
}
save(dimnamelist,dimnamelist.pca,meas,measpc,climateBins,halfBins,file = "objects.R")
```

## make all time series bootstrap replicates
```{r}
TSboot5.pca <- TSboot10.pca <- meas.pca <- TSboot5 <- TSboot10 <- 
  vector(mode = "list",length = length(meas))
names(TSboot5.pca) <- names(TSboot10.pca) <- names(meas.pca) <- names(TSboot5) <- names(TSboot10) <- names(meas)

M <- 1
N <- 1
for (m in M:length(meas)) {
  TSboot5[[m]] <- TSboot10[[m]] <- TSboot5.pca[[m]] <- TSboot10.pca[[m]] <- vector(mode = "list",length = length(meas[[m]]))
  names(TSboot5[[m]]) <- names(TSboot10[[m]]) <- names(TSboot5.pca[[m]]) <- names(TSboot10.pca[[m]]) <- names(meas[[m]])
  for (n in N:length(meas[[m]])) {
    TSboot5[[m]][[n]] <- bootReps(data = meas[[m]][[n]],reps = 1000,timebins = climateBins)
    TSboot10[[m]][[n]] <- bootReps(data = meas[[m]][[n]],reps = 1000,timebins = halfBins)
    names(TSboot5[[m]][n]) <- "meas.short"
    names(TSboot10[[m]][n]) <- "meas.long"
    if (all(c(m,n) == c(6,3))) { #skip PCA for bison calcanea, there's only one dimension
      TSboot5.pca[[m]][[n]] <- TSboot5[[m]][[n]]
      TSboot10.pca[[m]][[n]] <- TSboot10[[m]][[n]]
    } else {
      meas.pca[[m]][[n]] <- data.frame(Pit = meas[[m]][[n]][,"Pit"],
                                     pca.results[[m]][[n]]$x)
      TSboot5.pca[[m]][[n]] <- bootReps(data = meas.pca[[m]][[n]],
                                  reps = 1000,timebins = climateBins)
      TSboot10.pca[[m]][[n]] <- bootReps(data = meas.pca[[m]][[n]],
                                  reps = 1000,timebins = halfBins)
    }
    names(TSboot5.pca[[m]][n]) <- "pca.short"
    names(TSboot10.pca[[m]][n]) <- "pca.long"
  }
}
```


### reassemble
```{r}
reassemble <- function(element) {
  #TSboot5[[species]][[element]][[replicate]][[measurement]]$paleoTS
  result <- vector(mode = "list",length = length(element[[1]]))
  names(result) <- names(element[[1]])
  for (i in names(element[[1]])) {
    result[[i]] <- sapply(element, function(x) {
      return(x[[i]]$paleoTS)
    },simplify = F)
  }
  return(result)
}

reassembleDataset <- function(x){
  result <- x
  for (m in 1:5) {
    result[[m]] <- lapply(x[[m]],reassemble)
  }
  for (m in 7:length(x)) {
    result[[m]] <- lapply(x[[m]],reassemble)
  }
  result[[6]][[1]] <- reassemble(x[[6]][[1]])
  result[[6]][[2]] <- reassemble(x[[6]][[2]])
  result[[6]][[3]] <- list(Length = lapply(x[[6]][[3]], function(z) return(z$paleoTS)))
  return(result)
}

```

```{r}
load(file = "rep_TS/originalTSboot5.RData")
TSboot5 <- reassembleDataset(TSboot5)
for (m in 1:length(TSboot5)) {
  for (n in 1:length(TSboot5[[m]])) {
    names(TSboot5[[m]][[n]]) <- dimnamelist[[m]][[n]]
  }
}
save(TSboot5,file = "rep_TS/TSboot5.RData")
TSboot5 <- purrr::list_flatten(list_flatten(TSboot5))
save(TSboot5,file = "rep_TS/TSboot5_flat.RData")
names(TSboot5) -> flatnames
rm(TSboot5)

load(file = "rep_TS/originalTSboot10.RData")
TSboot10 <- reassembleDataset(TSboot10)
for (m in 1:length(TSboot10)) {
  for (n in 1:length(TSboot10[[m]])) {
    names(TSboot10[[m]][[n]]) <- dimnamelist[[m]][[n]]
  }
}
save(TSboot10,file = "rep_TS/TSboot10.RData")
TSboot10 <- list_flatten(list_flatten(TSboot10))
save(TSboot10,file = "rep_TS/TSboot10_flat.RData")
rm(TSboot10)

load(file = "rep_TS/originalTSboot5.pca.RData")
TSboot5.pca <- reassembleDataset(TSboot5.pca)
for (m in 1:length(TSboot5.pca)) {
  for (n in 1:length(TSboot5.pca[[m]])) {
    names(TSboot5.pca[[m]][[n]]) <- dimnamelist.pca[[m]][[n]]
  }
}
save(TSboot5.pca,file = "rep_TS/TSboot5.pca.RData")
TSboot5.pca <- list_flatten(list_flatten(TSboot5.pca))
save(TSboot5.pca,file = "rep_TS/TSboot5.pca_flat.RData")
rm(TSboot5.pca)

load(file = "rep_TS/originalTSboot10.pca.RData")
TSboot10.pca <- reassembleDataset(TSboot10.pca)
for (m in 1:length(TSboot10.pca)) {
  for (n in 1:length(TSboot10.pca[[m]])) {
    names(TSboot10.pca[[m]][[n]]) <- dimnamelist.pca[[m]][[n]]
  }
}
save(TSboot10.pca,file = "rep_TS/TSboot10.pca.RData")
TSboot10.pca <- list_flatten(list_flatten(TSboot10.pca))
save(TSboot10.pca,file = "rep_TS/TSboot10.pca_flat.RData")
rm(TSboot10.pca)
```
## get model outcomes for all replicates of all time series
don't forget to report model parameter estimates
```{r}
TSbootmodels5 <- TSbootmodels10 <- TSbootmodels5.pca <- TSbootmodels10.pca <- vector(mode="list",length=length(meas))
Z <- 1;M <- 1;N <- 1;P <- 1;Q <- 1
m <- n <- z <- p <- q <- 1
#m=species, n=element, z=replicate, p/q=dimension
```

```{r}
modelRepTS <- function(ts) {
  library(paleoTS)
  tsLength <- length(ts$tt)
  if (any(ts$vv == 0)) { pool <- TRUE } else { pool <- FALSE } 
  if (tsLength <= 5) { minb <- 2 } else { minb <- 3 }
  cl <- list(fnscale = -1.00000001)
  if (ts$vv[tsLength] == 0) { 
    punc <- fitGpunc(pool.var(ts,ret.paleoTS = TRUE),
                     minb = minb,pool = pool, cl = cl)
  } else {
    punc <- fitGpunc(ts,minb = minb,pool = pool,cl = cl)
  }
  grw <- opt.joint.GRW(ts,pool = pool)
  urw <- opt.joint.URW(ts,pool = pool)
  stasis <- opt.joint.Stasis(ts,pool = pool,cl = cl)
  params <- list(GRW = grw$parameters,
                 URW = urw$parameters,
                 Stasis = stasis$parameters,
                 Punc = punc$parameters)
  compare <- compareModels(grw, urw, stasis, punc)
  rownames(compare)[4] <- paste(rownames(compare)[4], ",Shift=",
                             punc$parameters[4], sep = "")
  return(list(compare = compare,params = params))
}
```

```{r}
failTS <- vector(mode="list")
failTS.index <- data.frame(array(data = NA, dim = c(1,5)))

# datacheck/debug block
TSboot5[[m]][[n]][[z]][[p]]$table
i <- length(failTS) + 1
failTS.index[i,] <- c(m,n,z,p,q)
failTS[[i]] <- TSboot5[[m]][[n]][[z]][[p]]$paleoTS

m -> M
n -> N
z + 1 -> Z
```

```{r}
load("rep_TS/TSboot5.RData")
for (m in M:length(TSboot5)) {
  for (n in N:length(TSboot5[[m]])) {
    for (z in Z:length(TSboot5[[m]][[n]])) {
      TSbootmodels5[[m]][[n]][[z]] <- vector(mode = "list",length = 1000)
      for (p in P:length(TSboot5[[m]][[n]][[z]])) {
        TSbootmodels5[[m]][[n]][[z]][[p]] <- 
          try(modelRepTS(TSboot5[[m]][[n]][[z]][[p]]$paleoTS))
      }
    }
  } 
}
save(TSbootmodels5,file = "rep_TS/TSbootmodels5.RData")
rm(TSboot5,TSbootmodels5)
```


```{r}
load("rep_TS/TSboot10.RData")
for (m in M:length(TSboot10)) {
  for (n in N:length(TSboot10[[m]])) {
    for (z in Z:length(TSboot10[[m]][[n]])) {
      TSbootmodels10[[m]][[n]][[z]] <- vector(mode = "list",length = 1000)
      for (p in P:length(TSboot10[[m]][[n]][[z]])) {
        TSbootmodels10[[m]][[n]][[z]][[p]] <- 
          try(modelRepTS(TSboot10[[m]][[n]][[z]][[p]]$paleoTS))
      }}}}
save(TSbootmodels10,file = "rep_TS/TSbootmodels10.RData")
rm(TSboot10,TSbootmodels10)
```


```{r}
load("rep_TS/TSboot5.pca.RData")
for (m in M:length(TSboot5.pca)) {
  for (n in N:length(TSboot5.pca[[m]])) {
    for (z in Z:length(TSboot5.pca[[m]][[n]])) {
      TSbootmodels5.pca[[m]][[n]][[z]] <- vector(mode = "list",length = 1000)
      for (q in Q:length(TSboot5.pca[[m]][[n]][[z]])) {
        if (all(c(m,n) == c(6,3))) {
          break
        } else {
          TSbootmodels5.pca[[m]][[n]][[z]][[q]] <- 
            try(modelRepTS(TSboot5.pca[[m]][[n]][[z]][[q]]$paleoTS))
        }}}}}
save(TSbootmodels5.pca,file = "rep_TS/TSbootmodels5.pca.RData")
rm(TSboot5.pca,TSbootmodels5.pca)
```


```{r}
load("rep_TS/TSboot10.pca.RData")
for (m in M:length(TSboot10.pca)) {
  for (n in N:length(TSboot10.pca[[m]])) {
    for (z in Z:length(TSboot10.pca[[m]][[n]])) {
      TSbootmodels10.pc[[m]][[n]][[z]] <- vector(mode = "list",length = 1000)
      for (p in P:length(TSboot10.pca[[m]][[n]][[z]])) {
        if (all(c(m,n) == c(6,3))) {
          break
        } else {
          TSbootmodels10.pca[[m]][[n]][[z]][[q]] <- 
            try(modelRepTS(TSboot10.pca[[m]][[n]][[z]][[q]]$paleoTS))
        }}}}}
save(TSbootmodels10.pca,file = "rep_TS/TSbootmodels10.pca.RData")
rm(TSboot10.pca,TSbootmodels10.pca)
```


```{r}
names(TSbootmodels5) <- names(TSbootmodels10) <- names(TSbootmodels5.pca) <- names(TSbootmodels10.pca) <- names(meas)
Z <- 1;M <- 1;N <- 1;P <- 1;Q <- 1
#m=species, n=element, z=replicate, p/q=dimension

for (m in M:length(TSboot5)) {
  names(TSbootmodels5[[m]]) <- names(TSbootmodels10[[m]]) <- 
    names(TSbootmodels5.pca[[m]]) <- names(TSbootmodels10.pca[[m]]) <- 
    names(meas[[m]])
  for (n in N:length(TSboot5[[m]])) {
    names(TSbootmodels5[[m]][[n]]) <- names(TSbootmodels10[[m]][[n]]) <- 
      names(TSbootmodels5.pca[[m]][[n]]) <- names(TSbootmodels10.pca[[m]][[n]]) <- 
      names(meas[[m]][[n]][4:ncol(meas[[m]][[n]])])
    for (z in Z:length(TSboot5[[m]][[n]])) {
      names(TSbootmodels5[[m]][[n]][[z]]) <- names(TSbootmodels10[[m]][[n]][[z]]) <-
        names(TSbootmodels5.pca[[m]][[n]][[z]]) <-
        names(TSbootmodels10.pca[[m]][[n]][[z]]) <- 1:1000
    }
  }
}
```

# summarize range of model outcomes for each time series

```{r}
#fix problem with dimension names
load(file = "rep_TS/TSbootmodels5.RData")
load(file = "rep_TS/TSboot5_flat.RData")
names(TSbootmodels5) <- names(TSboot5)
save(TSbootmodels5,file = "rep_TS/TSbootmodels5.RData")
rm(TSboot5,TSbootmodels5)

load(file = "rep_TS/TSbootmodels10.RData")
load(file = "rep_TS/TSboot10_flat.RData")
names(TSbootmodels10) <- names(TSboot10)
save(TSbootmodels10,file = "rep_TS/TSbootmodels10.RData")
rm(TSboot10,TSbootmodels10)

load(file = "rep_TS/TSbootmodels5.pca.RData")
load(file = "rep_TS/TSboot5.pca_flat.RData")
names(TSbootmodels5.pca) <- names(TSboot5.pca)
save(TSbootmodels5.pca,file = "rep_TS/TSbootmodels5.pca.RData")
rm(TSboot5.pca,TSbootmodels5.pca)

load(file = "rep_TS/TSbootmodels10.pca.RData")
load(file = "rep_TS/TSboot10.pca_flat.RData")
names(TSbootmodels10.pca) <- names(TSboot10.pca)
save(TSbootmodels10.pca,file = "rep_TS/TSbootmodels10.pca.RData")
rm(TSboot10.pca,TSbootmodels10.pca)
```

## compile model results
```{r}
require(rlist)
datanames <- c("TSbootmodels5","TSbootmodels5.pca","TSbootmodels10","TSbootmodels10.pca")
bestmods <- vector(mode = "list",length = length(datanames))
params <- vector(mode = "list",length = length(datanames))
names(bestmods) <- names(params) <- datanames

for (i in 1:4) {
  dataname <- datanames[i]
  load(file = paste0(c("rep_TS/",dataname,".RData"),collapse = ""))
  data <- get(dataname)
  bestmods[[i]] <- data.frame(unname(t(sapply(names(data),function(x) {
    temp <- unlist(strsplit(x,split = "_"))
    return(c(paste0(temp[1:2],collapse = "_"),temp[3],temp[4]))
  }))))
  colnames(bestmods[[i]]) <- c("species","element","measurement")
  bestmods[[i]]$L <- gsub(".*([[:digit:]]).*","\\1",dataname)
  bestmods[[i]]$model <- sapply(data,function(x)names(which.max(x$akaike)))
  params[[i]] <- vector(mode = "list",length = length(data))
  names(params[[i]]) <- names(data)
  for (j in 1:length(data)) {
    params[[j]] <- data.frame(t(cbind(data[[j]]$params$GRW,
                                      data[[j]]$params$URW,
                                      data[[j]]$params$Stasis,
                                      data[[j]]$params$Punc)))
    paramnames <- unlist(sapply(data[[j]]$params,colnames))
    rownames(params[[j]]) <- apply(cbind(gsub("[[:digit:]]","",names(paramnames)),
                                      paramnames),1,paste0,collapse = ".")
  }   
}
```

```{r}

```

